### ISSUE TITLE
Offer Delete are not working

### ISSUE THREAD

**Issue by kstmostofa** [me-shaon/laravel-crud-the-right-way#1]
# Offer Deleting is not working
Offer Deleting is showing deleted successfully but the offer is not deleting. because deleted_by and deleted_at are not added in the fillable property in the Offer model.

Note: need to add fillable property because here using update method. if use delete method then no need to add deleted_at in fillable property.

**Comment by me-shaon** [comment]
Fixed. Thanks.

**Comment by kstmostofa** [comment]
> Fixed. Thanks.

Welcome Brother
